{% set name = "spin" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spin-{{ version }}.tar.gz
  sha256: b1a0841527f94fdf10415ce4f3b273a36d62c229412aa5e81d4664473405f29c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  # You NEED to include the platform in the build string to avoid hash collisions
  # https://github.com/conda-forge/conda-forge.github.io/pull/1839#discussion_r1008679066
  string: unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [unix]
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [win]
  entry_points:
    - spin = spin.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - toml
    - colorama  # [win]
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - spin
  commands:
    - pip check
    # Error: cannot find [pyproject.toml]
    # - spin --help
  requires:
    - pip

about:
  home: https://github.com/scientific-python/spin
  summary: Developer tool for scientific Python libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
