{% set name = "spin" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spin-{{ version }}.tar.gz
  sha256: 4f00a9f3a91ee1adfeed553a4dfd37015bf54481161bcdaabff6ec6d5bbf5ffe

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - spin = spin.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - tomli
    - importlib-metadata >=7.0
    - colorama  # [win]
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - spin
  commands:
    - pip check
    # Error: cannot find [pyproject.toml]
    # - spin --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scientific-python/spin
  summary: Developer tool for scientific Python libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
    - stefanv
    - rgommers
    - lucascolley
