schema_version: 1

context:
  name: spin
  version: "0.14"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/spin-${{ version }}.tar.gz
  sha256: 1a5f6ce53699ef58bf893970ecb9d7f8814a8ca08da5d26e1391fe2a9fa04bcc

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - spin = spin.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click
    - tomli
    - importlib-metadata >=7.0
    - if: win
      then: colorama
    - if: unix
      then: __unix
    - if: win
      then: __win

tests:
  - python:
      imports:
        - spin
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Developer tool for scientific Python libraries
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scientific-python/spin

extra:
  recipe-maintainers:
    - hmaarrfk
    - stefanv
    - rgommers
    - lucascolley
