schema_version: 1

context:
  name: spin
  version: "0.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/spin-${{ version }}.tar.gz
  sha256: b8583e46361d4fd32b584cdeede9ffe5aa220f7cb2c6fc7e8f7ca16550b4ab62

build:
  number: 0
  noarch: python
  script: uv pip install --python ${{ PYTHON }} . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - spin = spin.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8,!=8.3.0,<8.4
    - tomli
    - importlib-metadata >=7.0
    - if: win
      then: colorama
    - if: unix
      then: __unix
    - if: win
      then: __win

tests:
  - python:
      imports:
        - spin
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Developer tool for scientific Python libraries
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scientific-python/spin

extra:
  recipe-maintainers:
    - stefanv
    - rgommers
    - lucascolley
