conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- linux_64
- win_64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
